rasp-rails/config/routes.rb
RaspRails::Application.routes.draw do

  match 'recent', to: 'application#recent', as: :recent
  match 'chart', to: 'application#chart', as: :chart

  root :to => 'application#index'

end

rasp-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index

  end

  def recent

  end

  def chart
    if params[:start_date]
      @from = params[:start_date]+" 00:00:01"
      @to = params[:end_date]+" 23:59:59"
    end
  end

end

rasp-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rasp-rails/app/views/application/chart.html.erb
<% if !@from.nil? and !@to.nil?%>
 <div id="data" class="true" data-from="<%= @from %>" data-to="<%= @to %>"></div>
<% end %>

<div class="small-12 columns">
  <h1>Dane historyczne</h1>

  <div class="panel">
    <form name="input" action="/chart" method="get">
      <input type="text" class="span2" value="<%= Date.yesterday.strftime("%Y-%m-%d") %>" data-date-format="yyyy-mm-dd" id="datepicker-from" name="start_date">
      <input type="text" class="span2" value="<%= Date.today.strftime("%Y-%m-%d") %>" data-date-format="yyyy-mm-dd" id="datepicker-to" name="end_date">
      <%#= link_to "Pokaż dane", "javascript:void(0);", id: "draw-chart" %>
      <input type="submit" value="Pokaż dane">
    </form>
  </div>
</div>

<div class="small-12 columns">
  <div id="notice"></div>
  <div id="chart"></div>
</div>

rasp-rails/app/views/application/index.html.erb
<h1>Rasp</h1>

<p>Projekt Rasp to...</p>

rasp-rails/app/views/application/recent.html.erb
<div class="small-12 columns">
  <h1>Aktualna temperatura</h1>
</div>

<div class="small-12 columns">
  <p>Rasp mówi, że temperatura to: <span id="temperature-value"></span> stopnia C.</p>
  <!-- <p>A temperatura starsza to: <span id="historic-temperature-value"></span> (z timestampem: <span id="historic-temperature-timestamp"></span> czyli <span id="historic-temperature-date"></span>)</p> -->
</div>

rasp-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Rasp Rails" %></title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,700,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= "#{controller_name} #{action_name} bg#{1+rand(4)}" %>">
    <%= render "partials/header" %>
    <div class="row">
      <div id="main-container" class="small-12 columns">
        <%= yield %>
      </div>
    </div>
    <%= render "partials/footer" %>
    <%= javascript_include_tag "application" %>
  </body>

</html>

rasp-rails/app/views/partials/_footer.html.erb
<footer>
  <div class="row">
    <div class="small-6 columns copyright">
      <p>&copy; 2014 Informatyka Stosowana UJ</p>
    </div>
    <div class="small-6 columns tag">
      <p>RASP<span> is it hot?</span></p>
      <p></p>
    </div>
  </div>
</footer>

rasp-rails/app/views/partials/_header.html.erb
<header>
  <div class="row">
    <div class="small-2 columns">
      <%= link_to "RASP", root_path, id: "logo" %>
    </div>
    <div class="small-10 columns">
      <ul class="menu">
        <li><%= link_to fa_icon("home"), root_path %></li>
        <li><%= link_to "Aktualna temperatura", recent_path %></li>
        <li><%= link_to "Dane historyczne", chart_path %></li>
      </ul>
    </div>
  </div>
</header>